version: "3.9"

services:
  load_balancer:
    build: ./load_balancer
    image: load_balancer
    container_name: load_balancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      mynet:
        aliases:
          - load_balancer
  
networks:
  mynet:
    name: mynet