version: "3.9"

services:
  
  load_balancer:
    build: ./load_balancer
    image: load_balancer
    container_name: load_balancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      mynet:
        aliases:
          - load_balancer
  
  # server:
  #   build: ./server
  #   image: server
  #   container_name: server1
  #   environment:
  #     - serverID=1
  #   ports:
  #     - "5001:5000"
  #   # networks:
  #   #   mynet:
  #   #     ipv4_address: 192.168.92.21
  
  # server2:
  #   build: ./server
  #   image: server
  #   container_name: server2
  #   environment:
  #     - serverID=2
  #   ports:
  #     - "5002:5000"
  # #   networks:
  # #     mynet:
  # #       ipv4_address: 192.168.92.22
  
  # server3:
  #   build: ./server
  #   image: server
  #   container_name: server3
  #   environment:
  #     - serverID=3
  #   ports:
  #     - "5003:5000"
  # #   networks:
  # #     mynet:
  # #       ipv4_address: 192.168.92.23

networks:
  mynet:
    name: mynet
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: "192.168.92.0/24"